# Generated by Django 5.1.2 on 2025-06-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProduc', models.CharField(max_length=100)),
                ('Talle', models.CharField(max_length=4)),
                ('Detalle', models.CharField(max_length=800)),
                ('Stock', models.BooleanField(default=True)),
            ],
        ),
    ]
