# Generated by Django 5.2.3 on 2025-06-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto_cantidad_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ImgProd',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Portada'),
        ),
    ]
