# Generated by Django 5.2.3 on 2025-08-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_producto_cantidad_alter_producto_imgprod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Cantidad',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.FloatField(default=0),
        ),
    ]
