# Generated by Django 5.2.3 on 2025-08-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_producto_cantidad_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
